log_dir: &log_dir logs

env:
  device: cuda
  WH: [640, 480]
  capture_fps: 15
  obs_fps: 15
  n_obs_steps: 1
  process_depth: False
  use_robot: True
  verbose: False
  num_points: 1000

  use_sam_hq: True
  sam_hq_checkpoint_path: perception/models/checkpoints/sam_hq_vit_h.pth

  sam_model: vit_b
  sam_checkpoint_path: perception/models/checkpoints/sam_vit_b_01ec64.pth

  # sam_model: vit_h
  # sam_checkpoint_path: perception/models/checkpoints/sam_vit_h_4b8939.pth

  grounding_dino_config: perception/models/config/GroundingDINO_SwinT_OGC.py
  grounding_dino_ckpt: perception/models/checkpoints/groundingdino_swint_ogc.pth

planner:
  log_dir: *log_dir
  prompt_fname: low_level_prompt
  few_shot_prompt_dir: flat_examples
  target_pcd_file: None
  temperature: 0.0
  model: gpt-4o
  max_tokens: 1024
  obs_x_center: 320 # 310
  obs_y_center: 240 # 196
  obs_x_scale: 0.8 # 0.6
  obs_y_scale: 0.8 # 0.42
  top_down_cam: 0
  tracking_cam: 2
  close_loop: True
  use_retriever: True
  mask_type: 'groundingdino' # 'sam'

camera:
# serial number sequence for fixed cameras: ['036322250488', '203522251843', '819612072758']
  front_cam:    '036322250488' # 0 (top-down)
  right_cam:    '203522251843' # 1 (tracking)
  left_cam :    '819612072758' # 2 (not being used)
  wrist_cam:    '308222301365' # (hand-eye calibration)